import type { Metadata } from "next";
import { ThemeModeToggle } from "@/components/organisms/theme-mode-toggle";
import BrandSloganStack from "@/components/atoms/brand/brand-slogan-stack";
import Link from "next/link";

export const metadata: Metadata = {
  title: "SocLif",
  description: "Generated by create next app",
};

export default function AuthLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <main className="container-min-h-fill flex flex-col py-10 px-4 gap-10 justify-center align-middle items-center">
      <div className="p-2 w-auto absolute top-0 right-0">
        <ThemeModeToggle />
      </div>
      <section className="md:grid md:grid-cols-12 md:w-full justify-center align-middle flex flex-col items-center gap-10 w-11/12">
        <div className="flex flex-col justify-center align-middle col-span-full md:col-span-7 items-center w-full gap-4 text-center">
          <h6 className="md:text-3xl text-2xl font-bold text-secondary hidden">
            Elevate Your <br />
            Social Hub with
          </h6>

          <Link href={"/"}>
            <BrandSloganStack className="w-full max-w-xs md:max-w-lg px-6 md:h-36" />
          </Link>
          <p className="text-base text-bw max-w-md font-light mt-5">
            Showcase your links, content, and collaborations effortlessly on one
            platform. Sign up now to amplify your social presence, connect with
            influence&apos;s, and embark on a journey of endless opportunities
          </p>
        </div>

        <div className="flex flex-col gap-6 w-full md:col-span-5 justify-center text-center md:text-left align-middle">
          {children}
        </div>
        <div className="flex flex-col gap-6 w-full md:col-span-5 justify-center text-center md:text-left align-middle"></div>
      </section>
    </main>
  );
}
