import type { Metadata } from "next";
import { ThemeProvider } from "@/next-shared/components/theme-provider";

import "../next-shared/styles/globals.css";
import { makeClient } from "@/next-shared/lib/apollo-provider";
import { ApolloNextAppProvider } from "@apollo/experimental-nextjs-app-support/ssr";
import { Toaster } from "@/next-shared/components/ui/toaster";

export const metadata: Metadata = {
  title: "MealPot",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <head />
      <body>
        <ApolloNextAppProvider makeClient={makeClient}>
          <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
            {children}
            <Toaster />
          </ThemeProvider>
        </ApolloNextAppProvider>
      </body>
    </html>
  );
}
