import type { Metadata } from "next";
import { ThemeProvider } from "@/next-shared/components/theme-provider";

import { GoogleOAuthProvider } from "@react-oauth/google";
import { makeClient } from "@/next-shared/lib/apollo-provider";
import { ApolloNextAppProvider } from "@apollo/experimental-nextjs-app-support/ssr";
import { Toaster } from "@/next-shared/components/ui/toaster";

export const metadata: Metadata = {
  title: "SocLif",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en w-full min-h-screen h-full">
      <head />
      <body className="w-full h-full">
        <GoogleOAuthProvider
          clientId={process.env.NEXT_PUBLIC_GOOGLE_CLIENT_ID || ""}
        >
          <ApolloNextAppProvider makeClient={makeClient}>
            <ThemeProvider
              attribute="class"
              defaultTheme="system"
              enableSystem
              disableTransitionOnChange
            >
              {children}
              <Toaster />
            </ThemeProvider>
          </ApolloNextAppProvider>
        </GoogleOAuthProvider>
      </body>
    </html>
  );
}
